### ISSUE TITLE
关于DatePicker指定日期后的bug

### ISSUE THREAD

**Issue by oicuivu** [iview/iview#1312]
### iView 版本号
http://unpkg.com/iview/dist/iview.min.js

### 操作系统/浏览器 版本号
 win7/58.0.3029.14 (64-bit)

### Vue 版本号
v2.3.0

### 复现步骤
1.为DatePicker设置默认日期（value/v-model）
2.点击DatePicker，重新选择一个日期
3.通过代码改变DatePicker的value
4.再次点击DatePicker
### 问题现象，以及你期望的结果是怎样的?
日期选择面板选中的日期，与DatePicker输入框里的日期不一致

**Comment by garzekangba** [comment]
我也有同样的问题！

**Comment by SergioCrisostomo** [comment]
This is Vue.js behaviour. 

If the value you pass by code is a string, then no change will be noticed and the `prop` will not change, and no reactive update will be fired: https://jsfiddle.net/Sergio_fiddle/bpcb6653/

If you want you can pass a Date Object and that way it will always fire since Date Objects are always new instances: https://jsfiddle.net/Sergio_fiddle/bpcb6653/1/
