### ISSUE TITLE
CSS fails to load fronts from CDN

### ISSUE THREAD

**Issue by ejfrancis** [iview/iview#1603]
If you try to load the CSS from a CDN, it fails to load the fonts. The issue is that the CSS file here (which is taken from [the docs](https://www.iviewui.com/docs/guide/install-en):

https://unpkg.com/iview@2.0.0/dist/styles/iview.css

Is trying to load the font via a url here:
```
src:url(fonts/ionicons.eot?v=2.0.0)
```

but that URL returns an "Invalid query: v=2.0.0"
https://unpkg.com/iview@2.0.0/dist/styles/fonts/ionicons.eot?v=2.0.0

If you remove the `?v=2.0.0` from the URL its accessible
https://unpkg.com/iview@2.0.0/dist/styles/fonts/ionicons.eot

**Comment by MartinKolarik** [comment]
This is caused by a recent breaking change in unpkg.com as they started blocking all requests containing a query string.

If you'd like, you are welcome to use [jsDelivr CDN](https://cdn.jsdelivr.net/npm/iview@2.0.0/dist/styles/iview.css), which works in a similar fashion but is strongly focused on production usage and never breaks any existing links.
