### ISSUE TITLE
I can't find all the properties from Docs, Could you please update the Docs

### ISSUE THREAD

**Issue by l619534951** [iview/iview#1830]
I can't find all properties from Docs，for example，The 'footerHide' properties of Modal ，I can't find that from Docs，could you please take some time to update the new properties to the Docs when you at leisure.

**Comment by SergioCrisostomo** [comment]
@l619534951 please be more specific about which methods/properties you do not found.

Our wish is to have the docs 100% updated, but it may be the case that things are missing. Please point us to the missing parts. You are also welcome to send a pull request with the fixes needed.

I'm closing this here since it belongs to https://github.com/iview/iview-doc
