### ISSUE TITLE
关于datePicker的datetime属性在ie11浏览器上初始值不显示time的问题？

### ISSUE THREAD

**Issue by tttttty** [iview/iview#1937]
我查看了iview2.3.2版本已经修复datePicker在ie11初始值不显示的问题，但是bug没有修复完全，在type=‘datetime’情况下，初始值设置“2014-02-02 10:10:10”这种情况时，在ie上是不显示的，如果初始值设置成‘2014-02-02’，ie浏览器上默认是‘2014-02-02 08:00:00’；其他浏览器都ok。

**Comment by SergioCrisostomo** [comment]
@tttttty thank you for reporting this. Could you provide a example so we can test this faster?

使用下面的在线链接可以快速创建示例 
https://codepen.io/anon/pen/KvJJdw

**Comment by tttttty** [comment]
https://codepen.io/anon/pen/qPZxdb#anon-signup
请用ie浏览器打开。

**Comment by tttttty** [comment]
https://codepen.io/tttttty/pen/veGRqq
这里是example，请使用ie浏览器打开。

**Comment by SergioCrisostomo** [comment]
@tttttty  tested your code now and found 2 problems:

 - `data(){` shorthand function syntax in object key that IE11 does not like
 - a bug in IE11 because of `Array.prototype.find` which IE11 does not have and babel preset `es2015` that iview uses doesn't polyfill

Can you please test this code https://jsfiddle.net/Sergio_fiddle/jpavpv3c/ and report if you still find the error you mentioned?
