### ISSUE TITLE
[Bug Report]Use modal component with Select component, drop down will not in it's position.

### ISSUE THREAD

**Issue by lbhsot** [iview/iview#3090]
### Environment
Mac Chrome 

### Reproduction link
[https://jsfiddle.net/jw2y3Lsb/](https://jsfiddle.net/jw2y3Lsb/)

### Steps to reproduce
Please open [https://jsfiddle.net/jw2y3Lsb/](url) and run the code.

And select the Select component below.

### What is expected?
Drop down should in it's position

### What is actually happening?
What's the drop down doing? Flying? May be it want to be free...

**Comment by zytim** [comment]
@lbhsot Hello, I have run your code and I think the bug is in your JS code but not the Select component. Drop down does not appear because the options data does not exist.

When I put your data into variable 'options1', the drop down is displayed. (need add prop 'transfer' to show all)

![image](https://user-images.githubusercontent.com/18764757/37322012-2604f2d0-26b6-11e8-941c-64e12bedcc1f.png)

**Comment by lbhsot** [comment]
@zytim thanks for your help.
